; PlatformIO Project Configuration File for LoRa Multi-Node (TX Nodes)

[env]
platform = atmelavr
board = feather32u4
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    4-20ma/ModbusMaster @ ^2.0.1

; Environment สำหรับ Node 1 (ต่อเซนเซอร์ DJLK-003AB ผ่าน RS485 Modbus RTU)
[env:node1]
build_flags = -D NODE_ID=1 -D USE_MODBUS_SENSOR

; Environment สำหรับ Node 2 (ต่อเซนเซอร์ Ultrasonic JSN-SR04T)
[env:node2]
build_flags = -D NODE_ID=2 -D USE_JSN_SR04T

; Environment สำหรับ Node 3 (ต่อเซนเซอร์ Ultrasonic HC-SR04)
[env:node3]
build_flags = -D NODE_ID=3 -D USE_HC_SR04
