; PlatformIO Project Configuration File for LoRa Multi-Node (TX Nodes)

[env]
platform = atmelavr
board = feather32u4
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0

; Environment สำหรับ Node 1
[env:node1]
build_flags = -D NODE_ID=1

; Environment สำหรับ Node 2
[env:node2]
build_flags = -D NODE_ID=2

; Environment สำหรับ Node 3
[env:node3]
build_flags = -D NODE_ID=3
